WEBFILEPATH="./webfile/"
JSPATH=f"{WEBFILEPATH}JS/"
CSSPATH=f"{WEBFILEPATH}CSS/"
ICONPATH=f"{WEBFILEPATH}ICON/"
IMAGEPATH=f"{WEBFILEPATH}images/"
DATABASEPATH="./database/"
HTMLPATH=f"{WEBFILEPATH}HTML/"
LICENSESPATH=f"{WEBFILEPATH}LICENSES/"
ARTICLEPATH=f"{WEBFILEPATH}ARTICLES/"
UPLOADEDARTICLEPATH=f"{ARTICLEPATH}UPLOADED/"
PREUPLOADPATH=f"{ARTICLEPATH}PREUPLOAD/"

# datdapath
DATABASEPATH="./database/"
UPDATEPATH=f"{DATABASEPATH}update/"

USERDB=f"{DATABASEPATH}user.db"
ARTICLEDB=f"{DATABASEPATH}article.db"
